### ISSUE TITLE
Example configuration file

### ISSUE THREAD

**Issue by stappersg** [isomer/erbium#11]
Hi,

Here another journal entry of my _exploring erbium expedition_  `;-)`.

In `man/erbium.conf.5` is an example configuration that did **not** work with a fresh `git clone` from early 2021.

I got
```
Error: Failed to load config from erbium.conf: Invalid Configuration: Policy contains unknown field 'dns-servers'
```

With
```diff
--- man/erbium.conf.5       2021-01-02 14:14:35.371601811 +0100
+++ man/erbium.conf.5       2021-01-02 19:24:32.162294063 +0100
@@ -361,8 +361,8 @@
         - prefix: 203.0.113.0/24
           next-hop: $self4
        policies:
-        - { match-hardware-address: 00:00:5E:00:53:01, apply-address: 198.51.100.110, dns-servers: null }
-        - { match-hardware-address: 00:00:5E:00:53:02, apply-address: 198.51.100.111, dns-servers: [8.8.8.8] }
+        - { match-hardware-address: 00:00:5E:00:53:01, apply-address: 198.51.100.110 }
+        - { match-hardware-address: 00:00:5E:00:53:02, apply-address: 198.51.100.111 }
 
      - apply-subnet: 203.0.113.0/24
        policies:
```
I got beyond that error.

I think it would be a good thing if `erbium` ships _copy and paste ready_ examples of configuration files. (It would got me sooner to  #10  `;-)`)

**Comment by isomer** [comment]
Ooops, thanks for the report, that's highly embarrassing.   I've added a test to make sure that this never happens again.  Hopefully this should be fixed at head for now and ever more.
