### ISSUE TITLE
Upgrading to nix 0.29

### ISSUE THREAD

**Issue by plugwash** [isomer/erbium#47]
Hi, 

I'm currently looking at updating the rust-nix package in Debian from 0.27 to 0.29. There seem to be a couple of changes that affect erbium-net.

The first is the return type of SockaddrIn::ip has changed, that was easy enough to deal with.

The second though is that the return type of RecvMsg::cmsgs has changed from `CmsgIterator<'_>` to `nix::Result<CmsgIterator<'_>>`. and the description has changed from."Iterate over the valid control messages pointed to by this msghdr." to "Iterate over the valid control messages pointed to by this msghdr. If allocated space for CMSGs was too small it is not safe to iterate, instead return an Error::ENOBUFS error."

It's not clear to me how this error should be dealt with. The function in which it is used doens't return a `Result` so propagating the error doesn't seem like an option, at least not without changing the API. In my patch I went for logging the issue (the same way unrecognised cmsgs are treated) and reuturning normally but I don't know if that is the best thing to do.

The patch I'm considering uploading to Debian is available at https://salsa.debian.org/rust-team/debcargo-conf/-/blob/affb21609699b9c04b9efeee9e78a40c3dcf16a4/src/erbium-net/debian/patches/nix-0.29.patch

**Comment by isomer** [comment]
Hmm.  That's supposed to decode all the the cmsg's that are there, if there aren't any valid ones, then warning and ignoring the problem seems like a reasonable solution.  The program should have allocated enough space, and if it hasn't then that's a bug.

**Comment by isomer** [comment]
I've pushed an update with your proposed fixes, HTH.

Thanks for the report.
