### ISSUE TITLE
doesn't handle IPv6 domain name servers - Add support for RDNSS

### ISSUE THREAD

**Issue by jelmer** [isomer/erbium#5]
It appears to just parse IP addresses as IPv4. If I try to configure an IPv6 address in erbium.conf, I get an invalid IP error:

```
Error: DHCP Config loading error: Failed to parse apply-dns-servers: iplist contains an invalid IP: String("2001:4860:4860::8888")
```

**Comment by isomer** [comment]
Hmm, this only implements dhcpv4, which I don't think has a way to specify v6 nameservers.  You would want to instead specify v6 nameservers using RDNSS on v6 RAs.   Supporting this is on my TODO list, but not implement yet.

**Comment by isomer** [comment]
Actually, lets use this to track adding RDNSS and friends.

**Comment by isomer** [comment]
RDNSS support was added in a75e9d6b0720b3eabfca1a5b758e482b50b9332c
