### ISSUE TITLE
Request: Publish as crate

### ISSUE THREAD

**Issue by stappersg** [isomer/erbium#9]
More a wish than request
 
Publish `erbium` at https://crates.io

**Comment by isomer** [comment]
I thought I had?  https://crates.io/crates/erbium

Is there something else I should be doing?

**Comment by stappersg** [comment]
On Mon, Nov 30, 2020 at 12:24:19PM -0800, Perry Lorier wrote:
> I thought I had?  https://crates.io/crates/erbium

Yes, it is there.
I don't known why my previous search at  crates.io didn't show it.


> Is there something else I should be doing?

:-)

Allow me to close this issue.
This is an email response.
(github.com login scheduled for later)
